'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Finestra.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finestra Virtual Desktops is already running. You can&apos;t run more than one instance of Finestra Virtual Desktops at one time..
        '''</summary>
        Friend ReadOnly Property AlreadyRunningError() As String
            Get
                Return ResourceManager.GetString("AlreadyRunningError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Already Running.
        '''</summary>
        Friend ReadOnly Property AlreadyRunningErrorTitle() As String
            Get
                Return ResourceManager.GetString("AlreadyRunningErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property applications_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_forward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_forward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desktop.
        '''</summary>
        Friend ReadOnly Property DesktopWord() As String
            Get
                Return ResourceManager.GetString("DesktopWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property ErrorTitle() As String
            Get
                Return ResourceManager.GetString("ErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finestra128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finestra128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finestra16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finestra16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finestra256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finestra256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finestra32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finestra32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finestra48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finestra48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaussianShadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaussianShadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while trying to register a hotkey. It is possible that another program is already using the hotkey..
        '''</summary>
        Friend ReadOnly Property HotkeyInUseError() As String
            Get
                Return ResourceManager.GetString("HotkeyInUseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Main_Icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Main_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset2 Symbol;}}
        '''{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl240\slmult1\lang9\f0\fs24 New Features\par
        '''\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-173\li360\sl240\slmult1\fs18 Screen edge switching\par
        '''{\pntext\f1\&apos;B7\tab}Window animations\par
        '''{\pntext\f1\&apos;B7\tab}Refined options dialog\par
        '''{\pntext\f1\&apos;B7\tab}Lots of misc. small improvements\par
        '''}
        ''' .
        '''</summary>
        Friend ReadOnly Property NewFeatures() As String
            Get
                Return ResourceManager.GetString("NewFeatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In order to aid organization, entire programs can be set to only appear on one desktop. If they try to open onto another desktop, they will be moved automatically to their proper place..
        '''</summary>
        Friend ReadOnly Property OptionsHelpDesktopRule() As String
            Get
                Return ResourceManager.GetString("OptionsHelpDesktopRule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some programs don&apos;t like to be hidden by virtual desktop programs. In many cases, however, you can fix these issues by adding the program to this list. All windows for these programs will be minimized before being hidden, and will be returned to their normal state when shown again. Most notably, Adobe CS applications should be placed here..
        '''</summary>
        Friend ReadOnly Property OptionsHelpMinimizeRule() As String
            Get
                Return ResourceManager.GetString("OptionsHelpMinimizeRule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hover over an option for more information..
        '''</summary>
        Friend ReadOnly Property OptionsHelpRule() As String
            Get
                Return ResourceManager.GetString("OptionsHelpRule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add programs using their executable&apos;s name, with or without the file extension. You can find process names in Task Manager&apos;s process list..
        '''</summary>
        Friend ReadOnly Property OptionsHelpRuleList() As String
            Get
                Return ResourceManager.GetString("OptionsHelpRuleList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sticky programs are programs that you can set to always appear on all desktops. They are essentially excluded from virtual desktop behavior..
        '''</summary>
        Friend ReadOnly Property OptionsHelpStickyRule() As String
            Get
                Return ResourceManager.GetString("OptionsHelpStickyRule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The application will now restart, causing all windows to move to the current desktop..
        '''</summary>
        Friend ReadOnly Property OptionsRestartWarning() As String
            Get
                Return ResourceManager.GetString("OptionsRestartWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application Restart.
        '''</summary>
        Friend ReadOnly Property OptionsRestartWarningTitle() As String
            Get
                Return ResourceManager.GetString("OptionsRestartWarningTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
