'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property NumDesktops() As Integer
            Get
                Return CType(Me("NumDesktops"),Integer)
            End Get
            Set
                Me("NumDesktops") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowIndicator() As Boolean
            Get
                Return CType(Me("ShowIndicator"),Boolean)
            End Get
            Set
                Me("ShowIndicator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property PreviewBackground() As Global.System.Drawing.Color
            Get
                Return CType(Me("PreviewBackground"),Global.System.Drawing.Color)
            End Get
            Set
                Me("PreviewBackground") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property FadeSpeed() As Single
            Get
                Return CType(Me("FadeSpeed"),Single)
            End Get
            Set
                Me("FadeSpeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VVDM Help.chm")>  _
        Public Property HelpName() As String
            Get
                Return CType(Me("HelpName"),String)
            End Get
            Set
                Me("HelpName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Z")>  _
        Public Property SwitcherKey() As Global.System.Windows.Forms.Keys
            Get
                Return CType(Me("SwitcherKey"),Global.System.Windows.Forms.Keys)
            End Get
            Set
                Me("SwitcherKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property SwitcherAcc() As Integer
            Get
                Return CType(Me("SwitcherAcc"),Integer)
            End Get
            Set
                Me("SwitcherAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property DesktopAcc() As Integer
            Get
                Return CType(Me("DesktopAcc"),Integer)
            End Get
            Set
                Me("DesktopAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DesktopNumpad() As Boolean
            Get
                Return CType(Me("DesktopNumpad"),Boolean)
            End Get
            Set
                Me("DesktopNumpad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstRun() As Boolean
            Get
                Return CType(Me("FirstRun"),Boolean)
            End Get
            Set
                Me("FirstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("W")>  _
        Public Property WinMenuKey() As Global.System.Windows.Forms.Keys
            Get
                Return CType(Me("WinMenuKey"),Global.System.Windows.Forms.Keys)
            End Get
            Set
                Me("WinMenuKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property WinMenuAcc() As Integer
            Get
                Return CType(Me("WinMenuAcc"),Integer)
            End Get
            Set
                Me("WinMenuAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property ArrowKeyAcc() As Integer
            Get
                Return CType(Me("ArrowKeyAcc"),Integer)
            End Get
            Set
                Me("ArrowKeyAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MultTrayIcons() As Boolean
            Get
                Return CType(Me("MultTrayIcons"),Boolean)
            End Get
            Set
                Me("MultTrayIcons") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CenterIndicWindow() As Boolean
            Get
                Return CType(Me("CenterIndicWindow"),Boolean)
            End Get
            Set
                Me("CenterIndicWindow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property IndicWinSize() As Integer
            Get
                Return CType(Me("IndicWinSize"),Integer)
            End Get
            Set
                Me("IndicWinSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MiniPrevSize() As Integer
            Get
                Return CType(Me("MiniPrevSize"),Integer)
            End Get
            Set
                Me("MiniPrevSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DesktopBackgrounds() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DesktopBackgrounds"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DesktopBackgrounds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DesktopBackgroundsData1() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DesktopBackgroundsData1"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DesktopBackgroundsData1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowMiniPrev() As Boolean
            Get
                Return CType(Me("ShowMiniPrev"),Boolean)
            End Get
            Set
                Me("ShowMiniPrev") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseDesktopBackgrounds() As Boolean
            Get
                Return CType(Me("UseDesktopBackgrounds"),Boolean)
            End Get
            Set
                Me("UseDesktopBackgrounds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SendToDeskNumpad() As Boolean
            Get
                Return CType(Me("SendToDeskNumpad"),Boolean)
            End Get
            Set
                Me("SendToDeskNumpad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property SendToDeskAcc() As Integer
            Get
                Return CType(Me("SendToDeskAcc"),Integer)
            End Get
            Set
                Me("SendToDeskAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AllMonitors() As Boolean
            Get
                Return CType(Me("AllMonitors"),Boolean)
            End Get
            Set
                Me("AllMonitors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UseMonitors() As String
            Get
                Return CType(Me("UseMonitors"),String)
            End Get
            Set
                Me("UseMonitors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("F9")>  _
        Public Property AllWindowsKey() As Global.System.Windows.Forms.Keys
            Get
                Return CType(Me("AllWindowsKey"),Global.System.Windows.Forms.Keys)
            End Get
            Set
                Me("AllWindowsKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property AllWindowsAcc() As Integer
            Get
                Return CType(Me("AllWindowsAcc"),Integer)
            End Get
            Set
                Me("AllWindowsAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property AppWindowsAcc() As Integer
            Get
                Return CType(Me("AppWindowsAcc"),Integer)
            End Get
            Set
                Me("AppWindowsAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("F10")>  _
        Public Property AppWindowsKey() As Global.System.Windows.Forms.Keys
            Get
                Return CType(Me("AppWindowsKey"),Global.System.Windows.Forms.Keys)
            End Get
            Set
                Me("AppWindowsKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("P")>  _
        Public Property MiniPrevKey() As Global.System.Windows.Forms.Keys
            Get
                Return CType(Me("MiniPrevKey"),Global.System.Windows.Forms.Keys)
            End Get
            Set
                Me("MiniPrevKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property MiniPrevAcc() As Integer
            Get
                Return CType(Me("MiniPrevAcc"),Integer)
            End Get
            Set
                Me("MiniPrevAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>sidebar</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>taskmgr</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property StickyPrograms() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("StickyPrograms"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("StickyPrograms") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>Photoshop</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Illustrator</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Fireworks</s"& _ 
            "tring>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Flash</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property MinimizePrograms() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("MinimizePrograms"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("MinimizePrograms") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-3000, -3000")>  _
        Public Property IconToolbarPosition() As Global.System.Drawing.Point
            Get
                Return CType(Me("IconToolbarPosition"),Global.System.Drawing.Point)
            End Get
            Set
                Me("IconToolbarPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IconToolbarIsVertical() As Boolean
            Get
                Return CType(Me("IconToolbarIsVertical"),Boolean)
            End Get
            Set
                Me("IconToolbarIsVertical") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseIconToolbar() As Boolean
            Get
                Return CType(Me("UseIconToolbar"),Boolean)
            End Get
            Set
                Me("UseIconToolbar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoCheckForUpdates() As Boolean
            Get
                Return CType(Me("AutoCheckForUpdates"),Boolean)
            End Get
            Set
                Me("AutoCheckForUpdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>Desktop 1</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Desktop 2</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Desktop 3</str"& _ 
            "ing>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Desktop 4</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property DesktopNames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DesktopNames"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DesktopNames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ProgramDesktopPrograms() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ProgramDesktopPrograms"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ProgramDesktopPrograms") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ProgramDesktopDesktops() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ProgramDesktopDesktops"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ProgramDesktopDesktops") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ProgramDesktops() As Global.System.Collections.Specialized.ListDictionary
            Get
                Return CType(Me("ProgramDesktops"),Global.System.Collections.Specialized.ListDictionary)
            End Get
            Set
                Me("ProgramDesktops") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ArrowKeyWinAcc() As Integer
            Get
                Return CType(Me("ArrowKeyWinAcc"),Integer)
            End Get
            Set
                Me("ArrowKeyWinAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DesktopBackgroundsData2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DesktopBackgroundsData2"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DesktopBackgroundsData2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CacheWindowThumbnails() As Boolean
            Get
                Return CType(Me("CacheWindowThumbnails"),Boolean)
            End Get
            Set
                Me("CacheWindowThumbnails") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TaskbarSwitching() As Boolean
            Get
                Return CType(Me("TaskbarSwitching"),Boolean)
            End Get
            Set
                Me("TaskbarSwitching") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowMiniPrevHover() As Boolean
            Get
                Return CType(Me("ShowMiniPrevHover"),Boolean)
            End Get
            Set
                Me("ShowMiniPrevHover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WasUpgraded() As Boolean
            Get
                Return CType(Me("WasUpgraded"),Boolean)
            End Get
            Set
                Me("WasUpgraded") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableWindowWatcher() As Boolean
            Get
                Return CType(Me("EnableWindowWatcher"),Boolean)
            End Get
            Set
                Me("EnableWindowWatcher") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EdgeSwitchEnable() As Boolean
            Get
                Return CType(Me("EdgeSwitchEnable"),Boolean)
            End Get
            Set
                Me("EdgeSwitchEnable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableSplashScreen() As Boolean
            Get
                Return CType(Me("EnableSplashScreen"),Boolean)
            End Get
            Set
                Me("EnableSplashScreen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property EdgeSwitchDelay() As Double
            Get
                Return CType(Me("EdgeSwitchDelay"),Double)
            End Get
            Set
                Me("EdgeSwitchDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WinAnimIn() As Boolean
            Get
                Return CType(Me("WinAnimIn"),Boolean)
            End Get
            Set
                Me("WinAnimIn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WinAnimOut() As Boolean
            Get
                Return CType(Me("WinAnimOut"),Boolean)
            End Get
            Set
                Me("WinAnimOut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EdgeSwitchMouseWrap() As Boolean
            Get
                Return CType(Me("EdgeSwitchMouseWrap"),Boolean)
            End Get
            Set
                Me("EdgeSwitchMouseWrap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WinAnimEnable() As Boolean
            Get
                Return CType(Me("WinAnimEnable"),Boolean)
            End Get
            Set
                Me("WinAnimEnable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.2")>  _
        Public Property WinAnimTime() As Double
            Get
                Return CType(Me("WinAnimTime"),Double)
            End Get
            Set
                Me("WinAnimTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DeskSwitchEnable() As Boolean
            Get
                Return CType(Me("DeskSwitchEnable"),Boolean)
            End Get
            Set
                Me("DeskSwitchEnable") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Finestra.My.MySettings
            Get
                Return Global.Finestra.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
